OrdererOrgs:
  - Name: Orderer
    Domain: project.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Producer
    Domain: producer.project.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Manufacturer
    Domain: manufacturer.project.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Deliverer
    Domain: deliverer.project.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Retailer
    Domain: retailer.project.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1